### ISSUE TITLE
Use with older thingworx versions

### ISSUE THREAD

**Issue by stefan-lacatus** [vrosu/thingworx-gitbackup-extension#4]
The 3.0 release of the GitBackup extension bumps the minimum Thingworx Version to 8.5.0. However, this release is too new, and many of the existing users did not migrate to it yet. 

Also, since this extension is used to sometimes migrate between Thingworx versions, maintaining compatibility to older thingworx versions (>8.1 for example) should be needed.

While I understand that the new version was only tested with 8.5.0, since nothing major changed, this should also be compatible with older versions.

Thanks,
Petrisor

**Comment by vrosu** [comment]
I don't have time to test this, but I will write here the steps needed for somebody who would want to update the extension to work with versions lower than 8.5:
-Unpack the GitBackupExtensionPack.zip. This results in 6 zip files.
-Unpack the GitBackupExtension.zip. This results in a metadata.xml and two folders.
-Edit metadata.xml and modify the minimumThingWorxVersion value to the one you want. It should be minimum 8.2.0, since that is the first ThingWorx version that supports the CustomCSS used in the mashups. Save the file
-Repack the GitBackupExtension.zip. Make sure that the archive has the exact same structure as before unpacking.
-Repack the GitBackupExtensionPack.zip. Make sure that the archive has the exact same structure as before unpacking.

**Comment by vrosu** [comment]
Closing due to existing time constraints. I am willing to accept Pull Requests if somebody confirms that it works.
